<?php

namespace ApiSikaBundle\Repository;

/**
 * ScanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScanRepository extends \Doctrine\ORM\EntityRepository
{
}
