# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # encoders:
    #     Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        default:
            entity:
                class: ApiSikaBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: true
            pattern:   ^/
            form_login:
                login_path: login
                check_path: /login_check
            logout:
                path: /logout
    # access_control:
    #     # require ROLE_ADMIN for /admin*
    #     - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/api/user/signup$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/api/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/api/, role: ROLE_ADMIN }
